<a href="https://colab.research.google.com/github/Bruno-TMS/python_tutoriais/blob/main/estudo_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a = np.arange(15)

In [5]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
a = a.reshape(3,5)

In [10]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
a.ndim

2

In [12]:
a.shape

(3, 5)

In [14]:
a.dtype.name

'int64'

In [15]:
a.itemsize

8

In [36]:
a.itemsize

8

In [17]:
a.size

15

In [18]:
type(a)

numpy.ndarray

In [23]:
b = np.array([6, 7,8])

In [24]:
b

array([6, 7, 8])

In [25]:
type(b)

numpy.ndarray

In [26]:
a =  np.array([2,3,4])

In [27]:
a

array([2, 3, 4])

In [28]:
a.dtype

dtype('int64')

In [29]:
b = np.array([1.2, 3.5, 5.1])

In [30]:
b.dtype

dtype('float64')

In [32]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [33]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [34]:
c = np.array([[1,2], [3,4]], dtype=complex)

In [35]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [49]:
np.empty((2,3), dtype=complex)

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [54]:
np.zeros((2,1), dtype=np.int16)

array([[0],
       [0]], dtype=int16)

In [59]:
np.arange(10, 30, 0.5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. ,
       26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

In [60]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [61]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [63]:
x  = np.linspace(0, 2*np.pi, 100)

In [64]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [65]:
f = np.sin(x)

In [66]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [68]:
tb = np.array([30,45,60,90])

In [69]:
tb

array([30, 45, 60, 90])

In [70]:
s = np.sin(tb)

In [71]:
s

array([-0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [74]:
tab2 = np.arange(0,181,15)

In [75]:
tab2

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180])

In [78]:
tab3 = np.linspace(0,180,9, dtype=np.int16)

In [79]:
tab3

array([  0,  22,  45,  67,  90, 112, 135, 157, 180], dtype=int16)

In [90]:
a = np.arange(24).reshape(2,3,4)

In [91]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [94]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [102]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [103]:
b

array([0, 1, 2, 3])

In [104]:
c = a-b

In [98]:
c

array([20, 29, 38, 47])

In [105]:
b**2

array([0, 1, 4, 9])

In [121]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))

In [122]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [123]:
a*=3

In [118]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [124]:
b+=a

In [125]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [126]:
a+=b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [127]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)

In [128]:
b.dtype.name

'float64'

In [129]:
b

array([0.        , 1.57079633, 3.14159265])

In [132]:
c = a + b
c
c.dtype.name

'float64'

In [133]:
d = np.exp(c*1j)
d
d.dtype.name

'complex128'

In [134]:
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [135]:
a.sum()

3.1057109529998157

In [136]:
a.min()

0.027559113243068367

In [137]:
a.max()

0.8277025938204418

In [139]:
b = np.arange(12).reshape(3,4)

In [140]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [141]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [142]:
b.min(axis=1)

array([0, 4, 8])

In [143]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [144]:
B = np.arange(3)

In [145]:
B

array([0, 1, 2])

In [146]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [147]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [150]:
C = np.array([2., -1., 4.])

In [151]:
np.add(B, C)

array([2., 0., 6.])

Indexing, slicing and iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [152]:
a = np.arange(10)**3

In [153]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [154]:
ols = [x**3 for x in range(10)]

In [155]:
ols

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [156]:
a[2]

8

In [157]:
a[2:5]

array([ 8, 27, 64])

In [159]:
a[:6:2] = 1000

In [160]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [161]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [162]:
def f(x, y):
  return 10*x+y

In [163]:
f(5,5)

55

In [166]:
b =np.fromfunction(f, (5,4), dtype=int)

In [167]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [168]:
b[2,3]

23

In [169]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [171]:
b[1:3,1]

array([11, 21])

In [172]:
b[-1]

array([40, 41, 42, 43])

Shape manipulation
Changing the shape of an array
An array has a shape given by the number of elements along each axis:

In [174]:
a = np.floor(10 *rg.random((3,4)))

In [175]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [176]:
a.shape

(3, 4)

In [177]:
a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [178]:
a.reshape(6,2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [179]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [180]:
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [181]:
a.T.shape

(4, 3)

In [182]:
a.shape

(3, 4)

In [183]:
a.reshape(3,-1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [187]:
a.reshape(-1,1).shape

(12, 1)

In [199]:
a = np.floor(10*rg.random((2,3)))

In [205]:
b = np.floor(10*rg.random((3,3)))

In [206]:
a

array([[6., 8., 5.],
       [2., 8., 5.]])

In [209]:
b

array([[6., 7.],
       [1., 8.],
       [1., 0.]])

In [211]:
a = np.floor(10*rg.random((2,12)))

In [212]:
a

array([[8., 8., 8., 4., 2., 0., 6., 7., 8., 2., 2., 6.],
       [8., 9., 1., 4., 8., 4., 5., 0., 6., 9., 8., 8.]])

In [217]:
np.hsplit(a,2)

[array([[8., 8., 8., 4., 2., 0.],
        [8., 9., 1., 4., 8., 4.]]),
 array([[6., 7., 8., 2., 2., 6.],
        [5., 0., 6., 9., 8., 8.]])]

In [219]:
np.hsplit(a,(3,10))

[array([[8., 8., 8.],
        [8., 9., 1.]]),
 array([[4., 2., 0., 6., 7., 8., 2.],
        [4., 8., 4., 5., 0., 6., 9.]]),
 array([[2., 6.],
        [8., 8.]])]